import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'
import Navbar from "./_components/Navbar";
import AuthSessionProv from "@/providers/authSession.provider";
import Providers from "@/providers/reactQuery.provider";
import { ToastContainer } from 'react-toastify'
import WishContextProvider from "@/wish.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Providers>
          <WishContextProvider>
          <ToastContainer/>
        <AuthSessionProv>
        <Navbar/>
      <div className="">
          {children}
      </div>  
      </AuthSessionProv>
      </WishContextProvider>
      </Providers>
      
      </body>
    </html>
  );
}
